const uid=()=>crypto.randomUUID();
const defaultState={
 sprints:[
  {id:uid(),name:'PC-00 – Projekt alapozás',startDate:'2026-06-26',endDate:'2026-07-03',status:'Folyamatban'},
  {id:uid(),name:'PC-01 – Tenant alapmodell',startDate:'2026-07-04',endDate:'2026-07-10',status:'Tervezett'},
  {id:uid(),name:'PC-02 – Felhasználói alapok',startDate:'2026-07-11',endDate:'2026-07-17',status:'Tervezett'},
  {id:uid(),name:'PC-03 – Auth alapok',startDate:'2026-07-18',endDate:'2026-07-24',status:'Tervezett'},
  {id:uid(),name:'PC-04 – Jogosultsági rendszer',startDate:'2026-07-25',endDate:'2026-07-31',status:'Tervezett'},
  {id:uid(),name:'PC-05 – Publikus tenant profil',startDate:'2026-08-01',endDate:'2026-08-07',status:'Tervezett'},
  {id:uid(),name:'PC-06 – Konfigurációs rendszer',startDate:'2026-08-08',endDate:'2026-08-14',status:'Tervezett'},
  {id:uid(),name:'PC-07 – Audit rendszer',startDate:'2026-08-15',endDate:'2026-08-21',status:'Tervezett'},
  {id:uid(),name:'PC-08 – Modul registry',startDate:'2026-08-22',endDate:'2026-08-28',status:'Tervezett'},
  {id:uid(),name:'PC-09 – Alap admin felület',startDate:'2026-08-29',endDate:'2026-09-04',status:'Tervezett'},
  {id:uid(),name:'PC-10 – Stabilizáció',startDate:'2026-09-05',endDate:'2026-09-11',status:'Tervezett'}
 ],
 tasks:[
  ['Backend projekt létrehozása','Backend','PC-00 – Projekt alapozás','Done','Magas'],['Repo struktúra kialakítása','DevOps','PC-00 – Projekt alapozás','In Progress','Magas'],['Docker Compose alap PostgreSQL-lel','DevOps','PC-00 – Projekt alapozás','To Do','Magas'],['.env konfiguráció és README','Dokumentáció','PC-00 – Projekt alapozás','To Do','Közepes'],['Health check endpoint','API','PC-00 – Projekt alapozás','To Do','Közepes'],['Swagger/OpenAPI bekötése','API','PC-00 – Projekt alapozás','To Do','Közepes'],
  ['Tenant entity és státuszok','Tenant','PC-01 – Tenant alapmodell','Backlog','Magas'],['Tenant slug validálás','Tenant','PC-01 – Tenant alapmodell','Backlog','Magas'],['Tenant CRUD endpointok','API','PC-01 – Tenant alapmodell','Backlog','Magas'],['EF Core migration tenant táblákhoz','Database','PC-01 – Tenant alapmodell','Backlog','Magas'],['Tenant repository/service réteg','Backend','PC-01 – Tenant alapmodell','Backlog','Közepes'],
  ['User entity létrehozása','Auth','PC-02 – Felhasználói alapok','Backlog','Magas'],['TenantUser kapcsolat','Tenant','PC-02 – Felhasználói alapok','Backlog','Magas'],['Tenant Admin külön profilként kezelése','Auth','PC-02 – Felhasználói alapok','Backlog','Magas'],['Felhasználó aktiválás/deaktiválás','Backend','PC-02 – Felhasználói alapok','Backlog','Közepes'],
  ['Regisztráció és bejelentkezés','Auth','PC-03 – Auth alapok','Backlog','Kritikus'],['Jelszó hash-elés','Auth','PC-03 – Auth alapok','Backlog','Kritikus'],['JWT vagy cookie session döntés és implementáció','Auth','PC-03 – Auth alapok','Backlog','Magas'],['Kijelentkezés','Auth','PC-03 – Auth alapok','Backlog','Közepes'],['Login audit esemény','Audit','PC-03 – Auth alapok','Backlog','Közepes'],
  ['Role és Permission entity','Auth','PC-04 – Jogosultsági rendszer','Backlog','Magas'],['Alap szerepkörök seedelése','Auth','PC-04 – Jogosultsági rendszer','Backlog','Magas'],['Authorization policy-k','Backend','PC-04 – Jogosultsági rendszer','Backlog','Magas'],['Jogosultsági tesztek','Tesztelés','PC-04 – Jogosultsági rendszer','Backlog','Közepes'],
  ['Publikus HÖK név, logó, bemutatkozás modell','Tenant','PC-05 – Publikus tenant profil','Backlog','Magas'],['Elérhetőségek és közösségi linkek','Tenant','PC-05 – Publikus tenant profil','Backlog','Közepes'],['Publikus tenant API ehok.hu/{slug} számára','API','PC-05 – Publikus tenant profil','Backlog','Magas'],['Üres állapotok támogatása HIP-hez','API','PC-05 – Publikus tenant profil','Backlog','Közepes'],
  ['Tenant settings modell','Backend','PC-06 – Konfigurációs rendszer','Backlog','Magas'],['Feature flag alapok','Backend','PC-06 – Konfigurációs rendszer','Backlog','Magas'],['Modul engedélyezés/tiltás','Backend','PC-06 – Konfigurációs rendszer','Backlog','Magas'],['Beállítások validálása','Tesztelés','PC-06 – Konfigurációs rendszer','Backlog','Közepes'],
  ['AuditLog entity','Audit','PC-07 – Audit rendszer','Backlog','Magas'],['Audit service','Audit','PC-07 – Audit rendszer','Backlog','Magas'],['Automatikus audit middleware','Audit','PC-07 – Audit rendszer','Backlog','Magas'],['Fejlesztői/admin hozzáférés előkészítése','Admin UI','PC-07 – Audit rendszer','Backlog','Közepes'],
  ['Module entity és ModuleKey','Backend','PC-08 – Modul registry','Backlog','Magas'],['TenantModule kapcsolat','Tenant','PC-08 – Modul registry','Backlog','Magas'],['Admin menü generálás előkészítése','Admin UI','PC-08 – Modul registry','Backlog','Közepes'],['HIP tartalom-slotok előkészítése','API','PC-08 – Modul registry','Backlog','Magas'],
  ['Admin login oldal','Admin UI','PC-09 – Alap admin felület','Backlog','Magas'],['Alap layout és sidebar','Admin UI','PC-09 – Alap admin felület','Backlog','Magas'],['Tenant profil szerkesztése UI-ból','Admin UI','PC-09 – Alap admin felület','Backlog','Magas'],['Felhasználók listája','Admin UI','PC-09 – Alap admin felület','Backlog','Közepes'],['Audit lista előnézet','Admin UI','PC-09 – Alap admin felület','Backlog','Közepes'],
  ['API response formátum egységesítése','API','PC-10 – Stabilizáció','Backlog','Magas'],['Logging egységesítése','Backend','PC-10 – Stabilizáció','Backlog','Magas'],['Seed adatok','Database','PC-10 – Stabilizáció','Backlog','Közepes'],['Tenant izoláció tesztelése','Tesztelés','PC-10 – Stabilizáció','Backlog','Kritikus'],['Dokumentáció frissítése','Dokumentáció','PC-10 – Stabilizáció','Backlog','Közepes']
 ].map(([title,area,sprint,status,priority])=>({id:uid(),title,area,sprint,status,priority})),
 roadmap:[
  {id:uid(),title:'Fejlesztői környezet lokálisan indítható',status:'Folyamatban'},
  {id:uid(),title:'Tenant alapmodell és publikus tenant adatok készek',status:'Tervezett'},
  {id:uid(),title:'Belépés, felhasználók és jogosultságok működnek',status:'Tervezett'},
  {id:uid(),title:'HIP alapváz kiszolgálható Platform Core adatokból',status:'Tervezett'},
  {id:uid(),title:'Audit és modul registry ráépíthető a további modulokra',status:'Tervezett'},
  {id:uid(),title:'Platform Core stabil alap HIP és modulfejlesztés előtt',status:'Tervezett'}
 ],
 notes:[{id:uid(),title:'Fejlesztési sorrend',body:'Platform Core után jöhet a vékony HIP alapváz. A hírek, események, naptárak és kérdőívek később modulokból töltik fel a HIP-et.',created:new Date().toLocaleDateString('hu-HU')}]
};
let state=load();
function load(){try{return JSON.parse(localStorage.getItem('ehokDevTrackerV3'))||structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem('ehokDevTrackerV3',JSON.stringify(state));renderAll()}
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function esc(v=''){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function badgeClass(v=''){const x=String(v).toLowerCase();if(x.includes('done')||x.includes('kész'))return'status-done';if(x.includes('blocked')||x.includes('blokkol'))return'status-blocked';if(x.includes('progress')||x.includes('folyamat')||x.includes('review'))return'status-progress';if(x.includes('kritikus'))return'priority-kritikus';return''}
function sprintPeriod(s){return [s.startDate,s.endDate].filter(Boolean).join(' – ')||'Nincs dátum'}
function sprintProgress(name){const tasks=state.tasks.filter(t=>t.sprint===name);const done=tasks.filter(t=>t.status==='Done').length;return tasks.length?Math.round(done/tasks.length*100):0}
function renderDashboard(){const total=state.tasks.length,done=state.tasks.filter(t=>t.status==='Done').length,prog=state.tasks.filter(t=>['In Progress','Review'].includes(t.status)).length,blocked=state.tasks.filter(t=>t.status==='Blocked').length;$('#totalTasks').textContent=total;$('#doneTasks').textContent=done;$('#progressTasks').textContent=prog;$('#blockedTasks').textContent=blocked;const percent=total?Math.round(done/total*100):0;$('#overallPercent').textContent=percent+'%';$('#overallBar').style.width=percent+'%';const statuses=['Backlog','To Do','In Progress','Review','Done','Blocked'];$('#statusProgress').innerHTML=statuses.map(s=>{const count=state.tasks.filter(t=>t.status===s).length,p=total?Math.round(count/total*100):0;return`<div class="module-row"><span>${s}</span><div class="mini-progress"><div style="width:${p}%"></div></div><b>${count}</b></div>`}).join('');const active=state.sprints.filter(s=>s.status==='Folyamatban'||s.status==='Csúszik').slice(0,4);$('#activeSprints').innerHTML=active.length?active.map(s=>`<div class="item-card"><div class="item-title">${esc(s.name)}</div><div class="meta">${esc(sprintPeriod(s))} · ${sprintProgress(s.name)}%</div></div>`).join(''):'<div class="empty">Nincs aktív sprint.</div>';const upcoming=state.tasks.filter(t=>t.status!=='Done').slice(0,6);$('#upcomingTasks').innerHTML=upcoming.length?upcoming.map(t=>`<div class="item-card"><div class="item-title">${esc(t.title)}</div><div class="meta">${esc(t.sprint||'Nincs sprint')} · ${esc(t.area||'Nincs terület')} · ${t.status}</div></div>`).join(''):'<div class="empty">Nincs nyitott feladat.</div>';$('#dashboardRoadmap').innerHTML=state.roadmap.slice(0,6).map(r=>`<div class="item-card"><div class="item-top"><div class="item-title">${esc(r.title)}</div><span class="badge ${badgeClass(r.status)}">${r.status}</span></div></div>`).join('')||'<div class="empty">Nincs mérföldkő.</div>'}
function renderSprints(){$('#sprintSelect').innerHTML='<option value="">Nincs sprint</option>'+state.sprints.map(s=>`<option>${esc(s.name)}</option>`).join('');$('#sprintList').innerHTML=state.sprints.map(s=>{const tasks=state.tasks.filter(t=>t.sprint===s.name),p=sprintProgress(s.name);return`<article class="item-card"><div class="item-top"><div><div class="item-title">${esc(s.name)}</div><div class="meta">${esc(sprintPeriod(s))} · ${tasks.length} feladat</div></div><span class="badge ${badgeClass(s.status)}">${s.status}</span></div><div class="progress" style="margin-top:14px"><div style="width:${p}%"></div></div><div class="actions"><button onclick="editSprint('${s.id}')">Szerkesztés</button><button class="delete" onclick="deleteSprint('${s.id}')">Törlés</button></div></article>`}).join('')||'<div class="empty">Még nincs sprint.</div>'}
function renderTasks(){const q=($('#taskSearch')?.value||'').toLowerCase(),list=state.tasks.filter(t=>[t.title,t.area,t.status,t.priority,t.sprint].some(v=>String(v||'').toLowerCase().includes(q)));$('#taskList').innerHTML=list.map(t=>`<article class="task-card"><div><div class="item-title">${esc(t.title)}</div><div class="task-meta"><span class="badge">${esc(t.area||'Nincs terület')}</span><span class="badge ${badgeClass(t.status)}">${t.status}</span><span class="badge ${badgeClass(t.priority)}">${t.priority}</span><span class="badge">${esc(t.sprint||'Nincs sprint')}</span></div></div><div class="actions"><select onchange="changeTaskStatus('${t.id}',this.value)">${['Backlog','To Do','In Progress','Review','Done','Blocked'].map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select><button onclick="editTask('${t.id}')">Szerkesztés</button><button class="delete" onclick="deleteTask('${t.id}')">Törlés</button></div></article>`).join('')||'<div class="empty">Nincs találat.</div>'}
function renderRoadmap(){$('#roadmapList').innerHTML=state.roadmap.map(r=>`<div class="timeline-item"><div class="item-top"><div class="item-title">${esc(r.title)}</div><span class="badge ${badgeClass(r.status)}">${r.status}</span></div><div class="actions"><button onclick="editRoadmap('${r.id}')">Szerkesztés</button><button class="delete" onclick="deleteRoadmap('${r.id}')">Törlés</button></div></div>`).join('')||'<div class="empty">Nincs mérföldkő.</div>'}
function renderNotes(){$('#noteList').innerHTML=state.notes.map(n=>`<article class="item-card"><div class="item-top"><div><div class="item-title">${esc(n.title)}</div><div class="meta">${esc(n.created)}</div></div></div><p>${esc(n.body)}</p><div class="actions"><button onclick="editNote('${n.id}')">Szerkesztés</button><button class="delete" onclick="deleteNote('${n.id}')">Törlés</button></div></article>`).join('')||'<div class="empty">Még nincs jegyzet.</div>'}
function renderAll(){renderDashboard();renderSprints();renderTasks();renderRoadmap();renderNotes()}
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+btn.dataset.view).classList.add('active-view');$('#pageTitle').textContent=btn.textContent}))
function resetForm(id,title,button){const f=$(id);f.reset();f.querySelector('[name=id]').value='';$(title).textContent=$(title).textContent.replace('Szerkesztés','Új');$(button).classList.add('hidden')}
$('#sprintForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.id){state.sprints=state.sprints.map(x=>x.id===f.id?f:x)}else state.sprints.push({id:uid(),...f});resetForm('#sprintForm','#sprintFormTitle','#cancelSprintEdit');save()});
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.id){state.tasks=state.tasks.map(x=>x.id===f.id?f:x)}else state.tasks.unshift({id:uid(),...f});resetForm('#taskForm','#taskFormTitle','#cancelTaskEdit');save()});
$('#roadmapForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.id){state.roadmap=state.roadmap.map(x=>x.id===f.id?f:x)}else state.roadmap.push({id:uid(),...f});resetForm('#roadmapForm','#roadmapFormTitle','#cancelRoadmapEdit');save()});
$('#noteForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.id){state.notes=state.notes.map(x=>x.id===f.id?{...x,title:f.title,body:f.body}:x)}else state.notes.unshift({id:uid(),title:f.title,body:f.body,created:new Date().toLocaleDateString('hu-HU')});resetForm('#noteForm','#noteFormTitle','#cancelNoteEdit');save()});
$('#cancelSprintEdit').onclick=()=>resetForm('#sprintForm','#sprintFormTitle','#cancelSprintEdit');$('#cancelTaskEdit').onclick=()=>resetForm('#taskForm','#taskFormTitle','#cancelTaskEdit');$('#cancelRoadmapEdit').onclick=()=>resetForm('#roadmapForm','#roadmapFormTitle','#cancelRoadmapEdit');$('#cancelNoteEdit').onclick=()=>resetForm('#noteForm','#noteFormTitle','#cancelNoteEdit');$('#taskSearch').addEventListener('input',renderTasks);
function fillForm(formId,obj){const f=$(formId);Object.entries(obj).forEach(([k,v])=>{const el=f.querySelector(`[name="${k}"]`);if(el)el.value=v??''});window.scrollTo({top:0,behavior:'smooth'})}
function editSprint(id){const x=state.sprints.find(s=>s.id===id);fillForm('#sprintForm',x);$('#sprintFormTitle').textContent='Sprint szerkesztés';$('#cancelSprintEdit').classList.remove('hidden')}
function editTask(id){const x=state.tasks.find(t=>t.id===id);fillForm('#taskForm',x);$('#taskFormTitle').textContent='Feladat szerkesztés';$('#cancelTaskEdit').classList.remove('hidden')}
function editRoadmap(id){const x=state.roadmap.find(r=>r.id===id);fillForm('#roadmapForm',x);$('#roadmapFormTitle').textContent='Mérföldkő szerkesztés';$('#cancelRoadmapEdit').classList.remove('hidden')}
function editNote(id){const x=state.notes.find(n=>n.id===id);fillForm('#noteForm',x);$('#noteFormTitle').textContent='Jegyzet szerkesztés';$('#cancelNoteEdit').classList.remove('hidden')}
function deleteSprint(id){state.sprints=state.sprints.filter(x=>x.id!==id);save()}function deleteTask(id){state.tasks=state.tasks.filter(x=>x.id!==id);save()}function deleteRoadmap(id){state.roadmap=state.roadmap.filter(x=>x.id!==id);save()}function deleteNote(id){state.notes=state.notes.filter(x=>x.id!==id);save()}function changeTaskStatus(id,status){state.tasks=state.tasks.map(t=>t.id===id?{...t,status}:t);save()}
function csvEscape(v=''){v=String(v??'').replace(/\r?\n/g,' ');return /[",;]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}
function toCsv(){const rows=[['type','id','title','name','startDate','endDate','status','priority','area','sprint','body','created']];state.sprints.forEach(x=>rows.push(['sprint',x.id,'',x.name,x.startDate,x.endDate,x.status,'','','','','']));state.tasks.forEach(x=>rows.push(['task',x.id,x.title,'','','',x.status,x.priority,x.area,x.sprint,'','']));state.roadmap.forEach(x=>rows.push(['roadmap',x.id,x.title,'','','',x.status,'','','','','']));state.notes.forEach(x=>rows.push(['note',x.id,x.title,'','','','','','','',x.body,x.created]));return rows.map(r=>r.map(csvEscape).join(';')).join('\n')}
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q&&c==='"'&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(!q&&(c===';'||c===',')){row.push(cell);cell='';continue}if(!q&&(c==='\n'||c==='\r')){if(c==='\r'&&n==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';continue}cell+=c}row.push(cell);rows.push(row);return rows.filter(r=>r.some(x=>x.trim()!==''))}
function fromCsv(text){const rows=parseCsv(text),head=rows.shift(),idx=k=>head.indexOf(k),next={sprints:[],tasks:[],roadmap:[],notes:[]};rows.forEach(r=>{const type=r[idx('type')];if(type==='sprint')next.sprints.push({id:r[idx('id')]||uid(),name:r[idx('name')],startDate:r[idx('startDate')],endDate:r[idx('endDate')],status:r[idx('status')]});if(type==='task')next.tasks.push({id:r[idx('id')]||uid(),title:r[idx('title')],area:r[idx('area')],sprint:r[idx('sprint')],status:r[idx('status')],priority:r[idx('priority')]});if(type==='roadmap')next.roadmap.push({id:r[idx('id')]||uid(),title:r[idx('title')],status:r[idx('status')]});if(type==='note')next.notes.push({id:r[idx('id')]||uid(),title:r[idx('title')],body:r[idx('body')],created:r[idx('created')]})});return next}
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([toCsv()],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ehok-dev-tracker.csv';a.click();URL.revokeObjectURL(a.href)});
$('#importInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state=fromCsv(reader.result);save()}catch{alert('Hibás CSV fájl.')}};reader.readAsText(file)});
$('#resetDemoBtn').addEventListener('click',()=>{if(confirm('Biztosan visszaállítod az alap adatokat?')){state=structuredClone(defaultState);save()}});
renderAll();
